typography_spectrum: 0.78998
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.875
  lightness: 0.25924169132485986
  saturation: 0.9714749085251242
  rhythmicContrast: 0.6716735123191029
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/8d451e25-1de2-4c78-9a75-da671b776094.jpg
  type: null
  appId: garciapineda
layout_spectrum: 0.93623
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Arturo Garcia
  email: artgarcia9@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/897f6277-0ee6-429a-b2e1-9f87a8ef8d0a.jpg
name: ARTURO GARCIA
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Company Danzante
    url: 'http://www.companydanzante.org/'
    type: external
  - name: Choreographer
    id: e15e7b8d-0a46-4f38-b697-cd8ad0e74afb
    type: content
  - name: Dancer
    id: 00909901-1a2d-43df-a7a5-0634affd1bef
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/954f7591-77b7-4c6f-8910-85f529f14aa6.jpg
title: 'Dancer, Choreographer, Teacher '
description: Know more and get involved
purpose: []
