typography_spectrum: 0.78998
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.875
  lightness: 0.25924169132485986
  saturation: 0.9714749085251242
  rhythmicContrast: 0.6716735123191029
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.93623
analytics:
  google: null
  facebook: null
  twitter: null
name: ARTUROGARCIA
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Company Danzante
    url: 'http://www.companydanzante.org/'
    type: external
favicon: null
title: 'Dancer, Choreographer, Teacher '
purpose: []
