name: ARTUROGARCIA
favicon: null
layout_spectrum: 0.93623
typography_spectrum: 0.78998
title: 'Dancer, Choreographer, Teacher '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.875
  lightness: 0.25924169132485986
  saturation: 0.9714749085251242
  rhythmicContrast: 0.6716735123191029
purpose: []
